#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: AWS-ACM-v3"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "AWS Certificate Manager v3",
  "ShortName": "AWS-ACM-v3",
  "Capability": "AWS-ACM-v3",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "UseDefaultSdkAuth",
      "DisplayName": "Use Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "A switch to enable the store to use Default SDK credentials"
    },
    {
      "Name": "DefaultSdkAssumeRole",
      "DisplayName": "Assume new Role using Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "UseDefaultSdkAuth",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "A switch to enable the store to assume a new Role when using Default SDK credentials"
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 Provider",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "A switch to enable the store to use an OAuth provider workflow to authenticate with AWS"
    },
    {
      "Name": "OAuthScope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "This is the OAuth Scope needed for Okta OAuth, defined in Okta"
    },
    {
      "Name": "OAuthGrantType",
      "DisplayName": "OAuth Grant Type",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "client_credentials",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "In OAuth 2.0, the term 'grant type' refers to the way an application gets an access token. In Okta this is `client_credentials`"
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Url",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "https://***/oauth2/default/v1/token",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "An optional parameter sts:ExternalId to pass with Assume Role calls"
    },
    {
      "Name": "OAuthClientId",
      "DisplayName": "OAuth Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The Client ID for OAuth."
    },
    {
      "Name": "OAuthClientSecret",
      "DisplayName": "OAuth Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The Client Secret for OAuth."
    },
    {
      "Name": "UseIAM",
      "DisplayName": "Use IAM User Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "A switch to enable the store to use IAM User auth to assume a role when authenticating with AWS"
    },
    {
      "Name": "IAMUserAccessKey",
      "DisplayName": "IAM User Access Key",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The AWS Access Key for an IAM User"
    },
    {
      "Name": "IAMUserAccessSecret",
      "DisplayName": "IAM User Access Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The AWS Access Secret for an IAM User."
    },
    {
      "Name": "ExternalId",
      "DisplayName": "sts:ExternalId",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "An optional parameter sts:ExternalId to pass with Assume Role calls"
    },
    {
      "Name": "DiscoveryRoleName",
      "DisplayName": "Discovery Role Name",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "KeyfactorACMDiscoveryRole",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "The IAM role name that exists in each target account. Used during cross-account Discovery to construct the Role ARN for cross-account access (arn:aws:iam::<account-id>:role/<this-value>). During a Discovery job this is supplied via the 'File name patterns to match' dialog field; this store property documents and defaults the value."
    }
  ],
  "EntryParameters": [
    {
      "Name": "ACM Tags",
      "DisplayName": "ACM Tags",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "The optional ACM tags that should be assigned to the certificate.  Multiple name/value pairs may be entered in the format of `Name1=Value1,Name2=Value2,...,NameN=ValueN`"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Optional"
}'

